language: php

services:
    - mysql

php:
    - 7.1
    - 7.2
    - 7.3

sudo: false

before_script:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
    - mysql -e 'DROP DATABASE IF EXISTS populator;'
    - mysql -e 'CREATE DATABASE populator;'

script:
    - mkdir -p build/logs
    - php vendor/bin/phpcs src/ --standard=PSR2 -n
    - php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
