language: php

php:
    - 7.1

sudo: false

before_script:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - mkdir -p build/logs
    - php vendor/bin/phpcs src/ --standard=PSR2 -n
    - php vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
