name: PHP extensions finder

on:
  push:
    branches:
      - master
  pull_request: null

jobs:
  extensions_finder:
    runs-on: ubuntu-latest
    name: PHP extensions finder

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Composer update
        run: composer update --no-progress --no-interaction

      - name: Install PHP extensions finder as dev dependency
        run: composer require dg/php-extensions-finder --dev

      - name: PHP extensions finder
        run: php vendor/dg/php-extensions-finder/php-extensions-finder check src tests
