name: PHPunit Myql 8

on:
  push:
    branches:
      - master
  pull_request: null

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2' ]

    name: PHPunit PHP ${{ matrix.php }}

    services:
      mysql:
        image: bitnami/mysql:8.0
        env:
          MYSQL_DATABASE: populator
          MYSQL_ROOT_PASSWORD: 123
          MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
          MYSQL_CHARACTER_SET: utf8mb4
          MYSQL_COLLATE: utf8mb4_general_ci
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Composer update
        run: composer update --no-progress --no-interaction

      - name: PHPunit
        run: vendor/bin/phpunit --coverage-text
        env:
          POPULATOR_ADAPTER: mysql
          POPULATOR_HOST: 127.0.0.1
          POPULATOR_PORT: ${{ job.services.mysql.ports[3306] }}
          POPULATOR_PASSWORD: 123
